version: '2.1'

services:
  doracloud:
    image: doracloud
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017